### ISSUE TITLE
How to show loading before it was ready?

### ISSUE THREAD

**Issue by imyellow** [rmartide/vue-google-login#12]
if using google ui render, the button will show after about 2 seconds, is any hook when it was ready to show?

**Comment by rmartide** [comment]
I just checked the documentation and there is not.

Sadly I have no control over when the button is rendered since it's done by google.

I also tried some things but without any luck. It seems like the rendering always takes some time and it's not tied to lifecycle hooks, the component is mounted but the button is still rendering.
