### ISSUE TITLE
Will SameSite cookie changes break this plugin?

### ISSUE THREAD

**Issue by serain** [rmartide/vue-google-login#18]
I'm no front-end dev and I'm not privy to details about the upcoming SameSite cookie changes.

I just noticed these warnings in Firefox and am wondering if we should expect this plugin to break soon?

```
Some cookies are misusing the recommended “sameSite“ attribute 2
Cookie “G_ENABLED_IDPS” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite cb=gapi.loaded_0:278:21
Cookie “G_AUTHUSER_H” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“
```

```
Cookie “SIDCC” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by rmartide** [comment]
Mmm, to be honest I have no idea, I guess we'll have to wait and see.

I think those warnings are for google to fix since those cookies are created automatically.

Thanks for bringing it up.

**Comment by serain** [comment]
Cool, I'm sure Google is on it.

**Comment by gsavalia** [comment]
@rmartide I'm using your module and have the same warning in Chrome, can you confirm this should be fixed on Google's side and cannot be done by adding a config in the module to set the cookies attributes to "SameSite=None; Secure".

Reading the previous messages, the problem has been around since at-least July so if Google is on it they are taking their time to fix! 

![Screenshot 2020-12-03 at 17 01 40](https://user-images.githubusercontent.com/40468987/101055251-0a547c00-358a-11eb-9a8f-2a575d50eb71.png)
