### ISSUE TITLE
Webpack UglifyJs is failing each time i run a production build

### ISSUE THREAD

**Issue by iabok** [rmartide/vue-google-login#2]
`ERROR in app.js from UglifyJs
Unexpected token: name (e) [./node_modules/vue-google-login/dist/vue-google-login.min.js:1,2044][app.js:58921,2001]
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by rmartide** [comment]
Hi, I tried to replicate the issue but I couldn't manage to do it.

I've updated the package to add some options and at the same time updated the tool I use to bundle the component.

Update it and try again.

You'll need to make some small adjustment since now accepts an object and not a string.

Let me know if it keeps happening.

**Comment by iabok** [comment]
@rmartide Thank you! I will make the adjustments and let you know how it goes!

**Comment by iabok** [comment]
@rmartide Sorry for the delay. I happened to pull your latest changes and did not help either but however got some hits on how to get past this https://github.com/JeffreyWay/laravel-mix/issues/790 and it helped
