### ISSUE TITLE
logoutButton makes the styled button disappear

### ISSUE THREAD

**Issue by pietrodicaprio** [rmartide/vue-google-login#6]
When setting the `logoutButton` prop to `true` the button style disappear and it has no text.

```Vue
<GoogleLogin
    :params="google.params"
    :renderParams="google.renderParams"
    :onSuccess="onGoogleSuccess"
    :onFailure="onGoogleFailure"
    :logoutButton="google.isLoggedIn"
    ></GoogleLogin>
```

https://i.imgur.com/kUmCEez.png

**Comment by pietrodicaprio** [comment]
If i put `false` directly to the prop 
```Vue
:logoutButton="false"
```
instead of reading a variable i get the button but with an horrible style:
https://i.imgur.com/2J5yjgR.png

so I just noticed the template code in https://github.com/rmartide/vue-google-login/blob/master/src/GoogleLogin.vue
 why this choice?

**Comment by rmartide** [comment]
Hi, sorry it took me so long to answer, I was bussy.

The thing is you can't use the rendered button to logout since it's the api who controls that button, I can't add a different behaviour.

What i've done to avoid that horrible style you mentioned is to always render a normal button if the logoutButton param is true.

I've updated the readme to clarify that.
